### ISSUE TITLE
Добавить в модель пользователя поле модератор

### ISSUE THREAD

**Issue by Flippi** [YegorAndVova/peep#13]

**Comment by YogurtTheHorse** [comment]
Что за поле, как должно работать?

**Comment by Flippi** [comment]
ну наверное true/false оно нужно и для тебя и для меня. Ты его должен мне возвращать на api/user (вместе со всей остальной инфой о пользователе) чтобы если это модератор то у него была кнопка перейти к админке, а тебе это поле нужно чтобы админ методы по удалению чего-то не могли юзать обычные юзеры
