### ISSUE TITLE
Добавить модели орудий в БД

### ISSUE THREAD

**Issue by Flippi** [YegorAndVova/peep#14]
Ak-47
Ak-74
MP4
Desert eagle
Пистолет Макарова
Пистолет ТТ
РПГ-7
Граната Ф1

**Comment by YogurtTheHorse** [comment]
Так это ты должен делать ручками)

**Comment by Flippi** [comment]
Так разве не должно быть в бд набора стандартных орудий?

**Comment by YogurtTheHorse** [comment]
Нет
