### ISSUE TITLE
Изменить респонс на метод api/orders

### ISSUE THREAD

**Issue by Flippi** [YegorAndVova/peep#16]
{
            "id": 2,
            "description": "asdasd",
            "author": " ИМЯ АВТОРА/КОМПАНИИ"
            "start": "2012-02-02T00:00:00.000Z",
            "duration": 123,
            "price" "1212412421',
            "delivery_place": "адрес",
            "order_list": "Состав закакза одним полем в формате: Название оружия - количество"
        },

**Comment by Flippi** [comment]
еще delivery_place не возвращаешь

**Comment by YogurtTheHorse** [comment]
> еще delivery_place не возвращаешь

Я возвращаю delivery_address
