### ISSUE TITLE
Добавить метод для получения списка всех диалогов пользователя

### ISSUE THREAD

**Issue by Flippi** [YegorAndVova/peep#26]

**Comment by Flippi** [comment]
формат ответа: 
[
{
name: "Имя пользователя"
chat-id; "id чата"
new: "4" - если имеются непрочитанные сообщения писать количество иначе 0 после перехода в диалог счетчик new у тебя на беке обнуляется
}


]

**Comment by YogurtTheHorse** [comment]
давай без непрочитанных, это будет сложнее реализовывать и ты сам задолбаешься еще

**Comment by Flippi** [comment]
Окей
