### ISSUE TITLE
сделать метод получения диалога по id

### ISSUE THREAD

**Issue by Flippi** [YegorAndVova/peep#27]
[
{
    name: "Имя пользователя"
    message: "Сообщение"
    date: "Время/Дата отправки"
    
}
{
    name: "Имя пользователя"
    message: "Сообщение"
    date: "Время/Дата отправки"
    
}
{
    name: "Имя пользователя"
    message: "Сообщение"
    date: "Время/Дата отправки"
    
}
]

**Comment by Flippi** [comment]
Не отправляешь date

**Comment by YogurtTheHorse** [comment]
не нужно
