### ISSUE TITLE
Добавить в модель заказа поля

### ISSUE THREAD

**Issue by Flippi** [YegorAndVova/peep#3]
Пример:
{"id":1241, "type_order":"Электронный аукцион", "price":120258954, "phase_box":"Подача заявок", "customer_name":"ГОСУДАРСТВЕННОЕ", "order_list":"Ак-47 - 5шт", "date_start":"24.22.2018", "date_end":"24.22.2018", "delivery_place":"Санкт-Петербург, ул. Пушкина-Ломоносова 124" }

**Comment by YogurtTheHorse** [comment]
вместо date_end у нас duration в дня

**Comment by YogurtTheHorse** [comment]
phase_box что такое?

**Comment by Flippi** [comment]
> phase_box что такое?

Этап закупки 
Либо подача заявок либо закупка завершена

**Comment by YogurtTheHorse** [comment]
там по дате можно считать это

**Comment by Flippi** [comment]
ты таким образом считаешь какие закупки активны, а какие в архиве?

**Comment by Flippi** [comment]
хотя лол, я так подумал это вообще не надо. На странице закупок у всех этап подача заявок, а в архиве закупка завершена. Чет я тупанул
